name: RTULib
version: '${version}'
main: com.github.ipecter.rtu.lib.RTULib
description: RTULib - Library Plugin for RTUPlugins
api-version: 1.17
authors: [ IPECTER ]
softdepend: [ PlaceholderAPI, Oraxen, ItemsAdder ]
commands:
  rtulib:
permissions:
  rtulib.reload:
    default: op
libraries:
  - net.kyori:adventure-platform-bukkit:4.3.2
  - net.kyori:adventure-text-minimessage:4.14.0
  - org.mongodb:bson:4.11.1
  - com.google.code.gson:gson:2.10.1
  - com.google.guava:guava:31.1-jre
  - org.apache.commons:commons-lang3:3.14.0